### ISSUE TITLE
Not all tables created

### ISSUE THREAD

**Issue by tomhath** [fhirbase/fhirplace#25]
When I installed fhirbase with docker about two months ago it created about 188 tables in the public schema. I installed it again today and it only created 15 tables. Did something change?

**Comment by niquola** [comment]
Hi now fhirbase is created only with few meta-tables, tables for other resources could be generated with fhir.generate_tables('{Patient, Encounter}') or if it will be called without params it would generate tables for all resources.

**Comment by tomhath** [comment]
Thanks for the quick response.. 

Fhirbase/fhirplace is really a nice implementation of FHIR, very well designed.
